### ISSUE TITLE
Releases don't contain communi-shared

### ISSUE THREAD

**Issue by brenns10** [communi/communi-desktop#105]
I'm working on creating an Arch Linux package for `communi-desktop`.  I noticed that when I download a tar.gz release, I don't get the `communi-shared` subrepository in the extracted contents.  Additionally, there are no corresponding versioned releases of `communi-shared` to download and extract into place.

Since Arch packaging involves a script that will build the package automatically from released source tarballs, it's important to have a method to build without `git submodule init --update`.  Do you think you could provide archives that include the subrepository, or provide releases of `communi-shared` that correspond with releases of this program?

(Also, this is a very cool project, and I've really been enjoying using Communi thus far.  I'm packaging it to make it easier to install on my other computers running Arch.  If you're OK with me publishing and maintaining the Arch package on their user repository, I would be willing to do so.  I would also be willing to provide you with the source so you could do it yourself, so whichever floats your boat.)

**Comment by Mikaela** [comment]
This seems to be the case of @GitHub being stupid and forcing everyone to use releases which don't include submodules and are always broken and cause issues like this (and many duplicates). I don't think there is anything @communi can do.

**Comment by brenns10** [comment]
From my own experience, project owners can upload their own archives and build artifacts to go with each release.  It's a bit less convenient than simply tagging and letting GitHub do it for you, but if the releases are meant to go to distribution packages, it's something that really ought to be done.

I almost didn't even try Communi since I wasn't able to find any packages for it.  Even as a developer who has experience with building C++ projects, I did not really want to bother with compiling this myself.  Good support for distribution packaging seems like a great way to get this project into more people's hands.

**Comment by jpnurmi** [comment]
Hi, I have pushed the missing tags to communi-shared.

**Comment by brenns10** [comment]
Thanks, @jpnurmi!  I have finished creating Arch Linux packages for libcommuni and communi-desktop.  They are on the Arch User Repository:

* [communi-desktop](https://aur.archlinux.org/packages/communi-desktop/) (regular release)
* [communi-desktop-git](https://aur.archlinux.org/packages/communi-desktop-git/) (latest git commit)
* [libcommuni](https://aur.archlinux.org/packages/libcommuni/) (regular release)
* [libcommuni-git](https://aur.archlinux.org/packages/libcommuni-git/) (latest git commit)

In case you're unfamiliar, the way the AUR works is that users submit PKGBUILD files, which are scripts that integrate with the Arch Build System to automatically create packages.  Packages submitted to the AUR are not hosted as binaries; instead, users download the PKGBUILD, run a command to build the package, and then install it (most people use programs that automate this, so installing an AUR package is no different than installing an official package).  So, what I submitted is a PKGBUILD file.

Since I submitted the packages, I'm currently the "maintainer".  That doesn't mean too much; just that I'll have to update the packages whenever you release new versions.  However, I don't want to step on your toes in terms of the ownership of your projects and packages.  Please let me know if you have any concerns about my packaging, or if you would like co-maintainership, or anything like that.  Otherwise, just close this issue!

**Comment by jpnurmi** [comment]
No concerns, I'm just glad someone is helping with the packages. :) Thank you for your contribution!
