### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bionade24** [communi/communi-desktop#141]
Last one was 4 years ago and is broken on Arch Linux.

**Comment by bionade24** [comment]
@jpnurmi Could you please consider doing this?

**Comment by jpnurmi** [comment]
Hi, was the issue fixed in the latest master? Does it work on Arch?

**Comment by bionade24** [comment]
> Hi, was the issue fixed in the latest master? Does it work on Arch?

Yes, it was fixed long ago. The current master runs fine for me, I use it on a daily basis.

**Comment by jpnurmi** [comment]
Ok, thanks! I pushed a [v3.6.0](https://github.com/communi/communi-desktop/releases/tag/v3.6.0) tag to sync with libcommuni.
