### ISSUE TITLE
Split views

### ISSUE THREAD

**Issue by ghost** [communi/communi-desktop#21]
Make it possible to split the view horizontally and/or vertically in the similar way than for example Qt Creator does.

**Comment by AlexandreBonneau** [comment]
Is there any reason why this was closed, since it looks like a regular feature request?

**Comment by jpnurmi** [comment]
Sorry for the lack of details here, but the feature was actually implemented. I recall it happened during some bigger refactoring, so there was probably no specific commit to link to. Anyway, try opening either the context menu over the chat view, or the options menu from the top right corner. Both menus contain "Split" and "Split side by side" actions.

![screen shot 2018-03-07 at 22 13 29](https://user-images.githubusercontent.com/140617/37118532-d66414e6-2254-11e8-9e41-1162d647006d.png)

**Comment by AlexandreBonneau** [comment]
Nice!
