### ISSUE TITLE
Global nick list with presence indicators

### ISSUE THREAD

**Issue by flatr0ze** [communi/communi-desktop#85]
I got this idea of suppressing the "Joined/Left" messages in the chat window by creating an array of users online (the key should probably be based on users' hostnames, not the nicknames). Such array should either be one-per-server or one-per-channel. (If the array is global it may be possible to get the list of other channels/servers a specific user is at, by hovering onto his/her nickname?)
We populate the array after joining the channel, then to avoid using loops, make the online marker to go "red" instead of printing message "left the channel" and turn it "green" instead of "joined the channel".
This could be a very nice feature to save space in the window,  and just to allow people to see if a person is still online. By hovering on that icon it may also tell the new nickname of that same user.
Leaving the classic text status messaging could be a nice option, since not all people like such features.

I'll try to mock something up, but don't think anything ready-to-merge will come out if I make it. I hope you like this idea, it could be a very nice addition to communi-desktop, I believe.

Thank you.

**Comment by jpnurmi** [comment]
When you have open queries, the target users are [monitored](http://ircv3.net/specs/core/monitor-3.2.html) on compliant servers (eg. Freenode). A query turns gray when the user is offline.

PS. Collecting all nicks of all channels to a single global list would not work very well for me, considering that I'm idling on plenty of massive channels with more than a thousand users on some of them.
