### ISSUE TITLE
Unable to establish secure connection

### ISSUE THREAD

**Issue by Venemo** [communi/communi-desktop#91]
I often get this error when trying to connect to Freenode:

```
[21:47:27] [ERROR] Unable to establish secure connection.
[21:47:27] [ERROR] The remote host closed the connection
```

It happens right after connecting to Freenode. Here's a full paste of the server buffer's contents when this happens:
http://pastebin.com/puR5zDWb

My connection parameters are:
*host:* irc.freenode.net
*port:* 7000
*secure:* enabled

**Comment by Venemo** [comment]
Got this error again and reproduced with `IRC_DEBUG=1`. Here's the output: http://pastebin.com/B9q8Zdw0

**Comment by Venemo** [comment]
Tried ports 7000 and 6697 and now getting the same result for both.

**Comment by jpnurmi** [comment]
Please pull the latest libcommuni & communi-desktop. I have tested with a bot that joined automatically 100 channels on connect. Sent commands are now queued and batched to avoid getting kicked out because of excessive flood.

**Comment by Venemo** [comment]
I've pulled it. Will report back about how it goes.

**Comment by jpnurmi** [comment]
It was actually the command queueing that was introduced to prevent excessive flood. A quit command was sometimes happily queued and then sent right after getting reconnected.
