### ISSUE TITLE
Add ability to filter backlog

### ISSUE THREAD

**Issue by mornfall** [communi/communi-desktop#93]
it'd be great if I could filter the backlog with keywords (a bit like what /lastlog in irssi does, but taking advantage of the GUI, so probably filtering on-the-fly would work best)

**Comment by Venemo** [comment]
We already have a search feature, so I modified the title to be only about filtering.

**Comment by jpnurmi** [comment]
You can now select "Filter" vs. "Search" from the menu in the search box.
