### ISSUE TITLE
Cannot tell if user is online or offline

### ISSUE THREAD

**Issue by khronosschoty** [communi/communi-desktop#96]
When using znc, your messages stay open, as well as your private messages, and this is desirable and a good thing; however, if you glance at your private messages, you cannot tell if their offline or online, like you can in other clients. It would be useful if like other clients, this was the case here.

**Comment by jpnurmi** [comment]
Sounds good. I guess http://ircv3.atheme.org/specification/monitor-3.2 is the way to go.

**Comment by jpnurmi** [comment]
20238da
