### ISSUE TITLE
[WIKI] Suggest using stable ZNC (checkout into tag) instead of master?

### ISSUE THREAD

**Issue by Mikaela** [communi/communi-desktop#98]
https://github.com/communi/communi-desktop/wiki/ZNC#build

**Comment by jpnurmi** [comment]
Or the 1.6 branch instead of a specific tag so one gets all latest fixes?

**Comment by Mikaela** [comment]
I don't think anyone is going to ever update after initial install unless maybe if there is a new release.

**Comment by jpnurmi** [comment]
https://github.com/communi/communi-desktop/wiki/ZNC/_compare/55073ee5c4268ebe8c449c2500ff19b232974530...3a2d2e9b44428c2d03ebc7ee50e14870829f1c7d
